//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAS.Lib.OPCClientControlsLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAS.Lib.OPCClientControlsLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address space branch node.
        /// </summary>
        internal static string BrowseElementNodeFolder {
            get {
                return ResourceManager.GetString("BrowseElementNodeFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag node.
        /// </summary>
        internal static string BrowseElementNodeTag {
            get {
                return ResourceManager.GetString("BrowseElementNodeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer node.
        /// </summary>
        internal static string ComputerTreeNodesToolTip {
            get {
                return ResourceManager.GetString("ComputerTreeNodesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string DeafaultSpecificationLabel {
            get {
                return ResourceManager.GetString("DeafaultSpecificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Space Dictionary File Error.
        /// </summary>
        internal static string DictionaryFileOpenError {
            get {
                return ResourceManager.GetString("DictionaryFileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.commsvr.com/DataPorter/Index.aspx#html/cd9b99cf-299d-47b0-a8a6-348d38f83e25.htm.
        /// </summary>
        internal static string Help_CreateSubscription {
            get {
                return ResourceManager.GetString("Help_CreateSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.commsvr.com/DataPorter/Index.aspx.
        /// </summary>
        internal static string Help_Default {
            get {
                return ResourceManager.GetString("Help_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.commsvr.com/OPC-Help/Index.aspx?topic=html/b8c5f048-bb7e-4742-b7f2-b61a77789ed9.htm.
        /// </summary>
        internal static string Help_Main {
            get {
                return ResourceManager.GetString("Help_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.commsvr.com/DataPorter/Index.aspx#html/662c67b6-580d-4f55-b8f6-20a4fdce79b7.htm.
        /// </summary>
        internal static string Help_SelectServerForm {
            get {
                return ResourceManager.GetString("Help_SelectServerForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.commsvr.com/DataPorter/Index.aspx#html/e8cbd036-5a13-4a3c-b6f1-637561d043fc.htm.
        /// </summary>
        internal static string Help_WriteTagSynchronously {
            get {
                return ResourceManager.GetString("Help_WriteTagSynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.commsvr.com/.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an exception during reading the properties from items.Default values are not set.Reason: .
        /// </summary>
        internal static string ItemValueListEditCtrl_property_error {
            get {
                return ResourceManager.GetString("ItemValueListEditCtrl_property_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default application that opens:
        ///{0} 
        ///may be mis-configured 
        ///(details: {1}). 
        ///Please navigate to: {0} manually..
        /// </summary>
        internal static string MainForm_DefaultAppMissing {
            get {
                return ResourceManager.GetString("MainForm_DefaultAppMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurs during receiving an update handler. This is not a serious problem it has only influence on messages displayed on debug tab, but if this Warning repeats very often please contact the technical support. Message:.
        /// </summary>
        internal static string MainFormUpdateEventHandlerException {
            get {
                return ResourceManager.GetString("MainFormUpdateEventHandlerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected text cannot be converted to a valid URL, because :  {0}..
        /// </summary>
        internal static string MesageBox_URLError {
            get {
                return ResourceManager.GetString("MesageBox_URLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to server tools strip..
        /// </summary>
        internal static string MessageBox_ConnectStrip {
            get {
                return ResourceManager.GetString("MessageBox_ConnectStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local network.
        /// </summary>
        internal static string NetworkTreeNodeToolTip {
            get {
                return ResourceManager.GetString("NetworkTreeNodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC server - connected.
        /// </summary>
        internal static string OPCServerTreeNodesToolTipConected {
            get {
                return ResourceManager.GetString("OPCServerTreeNodesToolTipConected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary of the a server address space..
        /// </summary>
        internal static string OPCServerTreeNodesToolTipDictionary {
            get {
                return ResourceManager.GetString("OPCServerTreeNodesToolTipDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC server - connection failed.
        /// </summary>
        internal static string OPCServerTreeNodesToolTipFailed {
            get {
                return ResourceManager.GetString("OPCServerTreeNodesToolTipFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC server - not connected.
        /// </summary>
        internal static string OPCServerTreeNodesToolTipNotConnected {
            get {
                return ResourceManager.GetString("OPCServerTreeNodesToolTipNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load server from configuration file..
        /// </summary>
        internal static string OpenDialogServeTitle {
            get {
                return ResourceManager.GetString("OpenDialogServeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load session from configuration file..
        /// </summary>
        internal static string OpenDialogSessionTitle {
            get {
                return ResourceManager.GetString("OpenDialogSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property node.
        /// </summary>
        internal static string PropertyNodeToolTip {
            get {
                return ResourceManager.GetString("PropertyNodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property value node.
        /// </summary>
        internal static string PropertyValueNodeToolTip {
            get {
                return ResourceManager.GetString("PropertyValueNodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Przegl_48 {
            get {
                object obj = ResourceManager.GetObject("Przegl_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.commsvr.com/rss/commservernews_en.rss.
        /// </summary>
        internal static string RSS {
            get {
                return ResourceManager.GetString("RSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save server configuration file..
        /// </summary>
        internal static string SaveDialogServerTitle {
            get {
                return ResourceManager.GetString("SaveDialogServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save session file..
        /// </summary>
        internal static string SaveDialogSessionTitle {
            get {
                return ResourceManager.GetString("SaveDialogSessionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription (active).
        /// </summary>
        internal static string SubscriptionTreeNodeToolTipActive {
            get {
                return ResourceManager.GetString("SubscriptionTreeNodeToolTipActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription node (disabled).
        /// </summary>
        internal static string SubscriptionTreeNodeToolTipDisabled {
            get {
                return ResourceManager.GetString("SubscriptionTreeNodeToolTipDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription (not active).
        /// </summary>
        internal static string SubscriptionTreeNodeToolTipNotActive {
            get {
                return ResourceManager.GetString("SubscriptionTreeNodeToolTipNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription node (off line).
        /// </summary>
        internal static string SubscriptionTreeNodeToolTipNotConnected {
            get {
                return ResourceManager.GetString("SubscriptionTreeNodeToolTipNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commserver@commserver.eu.
        /// </summary>
        internal static string Support_emailAddress {
            get {
                return ResourceManager.GetString("Support_emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, 
        ///I am interested in the following feature or  the following elements should be changed:.
        /// </summary>
        internal static string Support_MessageBody {
            get {
                return ResourceManager.GetString("Support_MessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC Viewer.
        /// </summary>
        internal static string Support_MessageCaption {
            get {
                return ResourceManager.GetString("Support_MessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC Viewer questions.
        /// </summary>
        internal static string Support_messageSubject {
            get {
                return ResourceManager.GetString("Support_messageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK to send email or Cancel otherwise..
        /// </summary>
        internal static string Support_MessageToBeShown {
            get {
                return ResourceManager.GetString("Support_MessageToBeShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node representing OPC tag - item value active.
        /// </summary>
        internal static string TagTreeNodeToolTipActive {
            get {
                return ResourceManager.GetString("TagTreeNodeToolTipActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node representing OPC tag - item in error state.
        /// </summary>
        internal static string TagTreeNodeToolTipError {
            get {
                return ResourceManager.GetString("TagTreeNodeToolTipError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node representing OPC tag - -item value not active.
        /// </summary>
        internal static string TagTreeNodeToolTipNotActive {
            get {
                return ResourceManager.GetString("TagTreeNodeToolTipNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy node.
        /// </summary>
        internal static string TreeNodeDummyLable {
            get {
                return ResourceManager.GetString("TreeNodeDummyLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC Environment.
        /// </summary>
        internal static string TreeNodeOPCEnvironmentText {
            get {
                return ResourceManager.GetString("TreeNodeOPCEnvironmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session OPC Root: root of all of the server connections and subscriptions created in this session..
        /// </summary>
        internal static string TreeNodeOPCEnvironmentToolTip {
            get {
                return ResourceManager.GetString("TreeNodeOPCEnvironmentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy node do represent any server object.
        /// </summary>
        internal static string TreeNodeToolTipDummy {
            get {
                return ResourceManager.GetString("TreeNodeToolTipDummy", resourceCulture);
            }
        }
    }
}
